#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	if [ ! -e /tmp/notify-boot-enqueued ]; then
		/usr/bin/notify "Роутер загрузился" && touch /tmp/notify-boot-enqueued
	fi
	procd_open_instance
	procd_set_param command /usr/bin/notify-worker
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger notify
}
